name: immortalwrt-x86-test

on:
  schedule:
    - cron: '0 20 * * 1' # 在中国时间每周一凌晨1点运行 (UTC时间是每周日下午5点)

  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
  targets_targets: immortalwrt-x86
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Compilation Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
          df -h

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        
    - name: Update feeds
      run: |
        cd openwrt
        # Add a feed source
        cat >> feeds.conf.default <<EOF
        # src-git kenzo https://github.com/kenzok8/openwrt-packages
        # src-git small https://github.com/kenzok8/small
        EOF
        # Add a feed source
        cat ./feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cd openwrt
        git clone https://Saxon-Sun:${{ secrets.pw }}@github.com/Saxon-Sun/Route-config-Files.git
        mv `pwd`/Route-config-Files/"$targets_targets"/* `pwd`/
        mv `pwd`/Route-config-Files/upload.sh `pwd`/
        cp -r `pwd`/Route-config-Files/public/* `pwd`/files/etc/config/
        chmod +x diy.sh
        ./diy.sh
        mv `pwd`/Route-config-Files/"$targets_targets"/.config `pwd`/
        make defconfig

    - name: Download package
      run: |
        cd openwrt
        make download -j16

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        #make -j1 V=s
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        rm -rf $(find ./bin/targets/ -type f -name "*rootfs*")
        #rm -rf build_dir
        df -h
        ls bin/targets/*/*
        echo "status=success" >> $GITHUB_OUTPUT

    - name: SSH connection to Actions
      uses: Saxon-Sun/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Prepare artifact
      run: |
        cd openwrt
        mkdir -p ./artifact/firmware
        mkdir -p ./artifact/package
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
        cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/

    - name: Upload firmware
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/
        chmod +x `pwd`/upload.sh
        `pwd`/upload.sh $targets_targets

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.pw }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 2
