name: immortalwrt-N1

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1日 UTC 0:00 (中国时间 08:00)
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH connection to Actions'
        required: false
        default: 'false'

env:
  TARGET_Name: immortalwrt-N1
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize Build Space
      uses: coder-xiaomo/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Initialize Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo timedatectl set-timezone Asia/Shanghai
        df -h

    - name: Clone Source Code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        git clone --depth 1 https://Saxon-Sun:${{ secrets.pw }}@github.com/Saxon-Sun/Route-config-Files.git
        df -hT $PWD

    - name: Configure Feeds
      run: |
        cd openwrt
        rm -rf package/luci-app-amlogic
        git clone --depth 1 https://github.com/ophub/luci-app-amlogic.git package/luci-app-amlogic
        cp -r Route-config-Files/$TARGET_Name/* .
        chmod +x Route-config-Files/diy/*.sh
        mv Route-config-Files/diy/*.sh .
        ./Add-Source.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply Custom Configuration
      run: |
        cd openwrt
        cp -r Route-config-Files/public/* files/etc/
        ./diy-n1.sh
        mv Route-config-Files/$TARGET_Name/.config .
        make defconfig

    - name: Enable SSH (Optional)
      if: github.event.inputs.ssh == 'true'
      uses: Saxon-Sun/ssh2actions@main
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Download Dependencies
      id: package
      run: |
        cd openwrt
        make download -j$(nproc)

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        #make -j1 V=s
        du -ah ./build_dir/target* | sort -rh | awk 'NR<=20'
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin
        ls bin/targets/*/*
        rm -rf build_dir
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        df -h
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Package Armvirt as OpenWrt
      if: steps.compile.outputs.status == 'success' && !cancelled()
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        WHOAMI: Saxon

    - name: Prepare Artifacts
      if: env.PACKAGED_STATUS == 'success' && !cancelled()
      run: |
        cd openwrt
        mkdir -p artifact/firmware
        mkdir -p artifact/package
        ls -lh /opt/openwrt_packit/output
        find /opt/openwrt_packit/output -type f -exec cp -f {} artifact/firmware/ \;
        find artifact/firmware/ -type f -name "*rootfs*" -exec rm -f {} \;
        ./upload.sh $TARGET_Name

    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.pw }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 2