name: immortalwrt-N1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  targets_targets: immortalwrt-N1
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        #root-reserve-mb: 5120
        #swap-size-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Compilation Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
          df -h

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: |
        cd openwrt
        sudo -E apt-get -qq install subversion
        svn co https://github.com/ophub/luci-app-amlogic/trunk/luci-app-amlogic ./package/luci-app-amlogic
        # Add a feed source
        cat >> feeds.conf.default <<EOF
        # src-git kenzo https://github.com/kenzok8/openwrt-packages
        # src-git small https://github.com/kenzok8/small
        EOF
        # Add a feed source
        cat ./feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cd openwrt
        git clone https://Saxon-Sun:${{ secrets.pw }}@github.com/Saxon-Sun/Route-config-Files.git
        mv `pwd`/Route-config-Files/"$targets_targets"/* `pwd`/
        mv `pwd`/Route-config-Files/upload.sh `pwd`/
        cp -r `pwd`/Route-config-Files/public/* `pwd`/files/etc/config/
        chmod +x diy.sh
        ./diy.sh
        mv `pwd`/Route-config-Files/"$targets_targets"/.config `pwd`/
        make defconfig

    - name: SSH connection to Actions
      uses: Saxon-Sun/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j16
        
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) 2>&1|tee ./xxx.log || make -j1 V=s 2>&1|tee ./xxx.log
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        #make -j1 V=s |tee ./xxx.log
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        rm -rf $(find ./bin/targets/ -type f -name "*rootfs*")
        ls bin/targets/*/*
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Package Armvirt as OpenWrt
      if: steps.compile.outputs.status == 'success' && !cancelled()
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_VERSION_NAME: 6.1.9
        WHOAMI: Saxon

    - name: Prepare artifact
      if: env.PACKAGED_STATUS == 'success' && !cancelled()
      run: |
        cd openwrt/
        ls /opt/openwrt_packit/output
        rm -rf /opt/openwrt_packit/output/*.tar.gz
        mv /opt/openwrt_packit/output/* ./artifact/package/
        chmod +x `pwd`/upload.sh
        `pwd`/upload.sh $targets_targets

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 2
