name: Phicomm-N1手动打包

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

      Bin-url:
        description: 'Bin download Url'
        required: false

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6144
        swap-size-mb: 4096
        remove-dotnet: 'true'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Compilation Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get update
          sudo -E apt-get -y install tmate curl gawk gperf intltool lrzsz mkisofs nano patch pkgconf scons squashfs-tools subversion texinfo uglifyjs unzip vim wget
          df -h

    - name: Load Bin
      run: |
        mkdir openwrt
        cd openwrt
        git clone https://Saxon-Sun:${{ secrets.pw }}@github.com/Saxon-Sun/Route-config-Files.git
        mv `pwd`/Route-config-Files/Phicomm-N1/* `pwd`/
        wget -q ${{ inputs.Bin-url }}

    - name: SSH connection to Actions
      uses: Saxon-Sun/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Package Armvirt as OpenWrt
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_VERSION_NAME: 6.1.9
        WHOAMI: Saxon

    - name: Prepare artifact
      run: |
        cd openwrt/
        chmod +x `pwd`/upload.sh
        `pwd`/upload.sh

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_firmware
        path: ./openwrt/artifact/firmware
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 2
