#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6144
        swap-size-mb: 4096
        remove-dotnet: 'true'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master 

    - name: Install Compilation Dependencies
      id: compile
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "successed"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 3
